/* Generated by Together */

#ifndef SNOWMISSIONTHEATER_H
#define SNOWMISSIONTHEATER_H
#include "MissionTheater.h"
class SnowMissionTheater : public MissionTheater {
public:    

    SnowMissionTheater();
};
#endif //SNOWMISSIONTHEATER_H
